### PR TITLE
detection enhancement

### PR DESCRIPTION
**Pull request by D-Ace0**
This pull request enhances the functionality of Graphw00f to detect certain GraphQL APIs that were previously undetectable. Specifically java-based ones or anyone that uses 'classification' in the error JSON response. Also, Adding endpoints that i saw in the wild.

### CODE REVIEW

**Comment by dolevf** [comment]
HI @D-Ace0,

On first glance, it seems that the screenshot from https://github.com/dolevf/graphw00f/issues/39 shows that `extensions` is part of the `errors` response, which I think is not standardized with the GraphQL spec as per https://spec.graphql.org/October2021/#sec-Response-Format, which is why graphw00f did not detect this.

Do you know which Java GraphQL server this is? I can certainly merge this, but I'm curious since this is not something I've encountered before.

**Comment by D-Ace0** [comment]
Hello @dolevf,
I searched for this as well and i thought it might be Springboot because extensions field there exists by default not as the specs you sent. I searched for this so maybe we can add a new fingerprint to the tool. also for your curiosity about this behavior, this is a public program on bugcrowd called upwork.
Error handling in Spring Boot graphql: https://www.baeldung.com/spring-graphql-error-handling

**Comment by D-Ace0** [comment]
@dolevf 
something to note is i said extensions is there by default as when you read the article you will find this key always exists with either null value or with a value seems fit for developers, which means no restrictions for it. they mentioned the following about extensions:-
```The response map may contain an additional component called extensions, which is a map object. The component facilitates the implementors to provide other custom contents in the response as they see fit. Hence, there are no additional restrictions on its content format.```

**Comment by dolevf** [comment]
Thanks for your contribution!

**Review by misscriss — COMMENTED** [review]
@cataliniovita

**Pull request merged**
